/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : string,
  'authorPrincipal' : UserId,
  'postId' : PostId,
}
export type CommentId = bigint;
export interface ConversationPreview {
  'lastMessage' : DirectMessageView,
  'unreadCount' : bigint,
  'partner' : UserId,
}
export interface DirectMessageView {
  'id' : bigint,
  'to' : UserId,
  'from' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'readByRecipient' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface FollowRequest {
  'id' : bigint,
  'to' : UserId,
  'status' : FollowRequestStatus,
  'from' : UserId,
  'createdAt' : Timestamp,
}
export type FollowRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface Notification {
  'id' : NotificationId,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'fromPrincipal' : UserId,
  'postId' : [] | [PostId],
}
export type NotificationId = bigint;
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'newFollower' : null };
export interface Page {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<Profile>,
}
export interface Page_1 {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<Post>,
}
export interface Page_2 {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<Comment>,
}
export interface Page_3 {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<Notification>,
}
export interface Page_4 {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<UserId>,
}
export interface Post {
  'id' : PostId,
  'photoBlob' : [] | [ExternalBlob],
  'likeCount' : bigint,
  'createdAt' : Timestamp,
  'caption' : string,
  'commentCount' : bigint,
  'authorPrincipal' : UserId,
}
export type PostId = bigint;
export interface PostInput {
  'photoBlob' : [] | [ExternalBlob],
  'caption' : string,
}
export interface Profile {
  'bio' : string,
  'postCount' : bigint,
  'principal' : UserId,
  'username' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export interface ProfileInput {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'avatarBlob' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[PostId, string], Comment>,
  'approveFollowRequest' : ActorMethod<[UserId], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[PostInput], Post>,
  'declineFollowRequest' : ActorMethod<[UserId], boolean>,
  'deleteComment' : ActorMethod<[PostId, CommentId], boolean>,
  'deletePost' : ActorMethod<[PostId], boolean>,
  'followUser' : ActorMethod<[UserId], boolean>,
  'getCallerProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<
    [UserId, bigint, bigint],
    Array<DirectMessageView>
  >,
  'getExploreFeed' : ActorMethod<[bigint, bigint], Page_1>,
  'getFollowerProfiles' : ActorMethod<[UserId, bigint, bigint], Page>,
  'getFollowers' : ActorMethod<[UserId, bigint, bigint], Page_4>,
  'getFollowing' : ActorMethod<[UserId, bigint, bigint], Page_4>,
  'getFollowingProfiles' : ActorMethod<[UserId, bigint, bigint], Page>,
  'getHomeFeed' : ActorMethod<[bigint, bigint], Page_1>,
  'getMyFollowRequests' : ActorMethod<[], Array<FollowRequest>>,
  'getNotifications' : ActorMethod<[bigint, bigint], Page_3>,
  'getPendingRequestCount' : ActorMethod<[], bigint>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'getRequestStatus' : ActorMethod<[UserId], [] | [FollowRequestStatus]>,
  'getSuggestedUsersWithFollowing' : ActorMethod<[bigint, bigint], Page>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'isLiked' : ActorMethod<[PostId], boolean>,
  'listComments' : ActorMethod<[PostId, bigint, bigint], Page_2>,
  'listConversations' : ActorMethod<[], Array<ConversationPreview>>,
  'listPostsByAuthor' : ActorMethod<[UserId, bigint, bigint], Page_1>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markConversationRead' : ActorMethod<[UserId], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'registerUser' : ActorMethod<[ProfileInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string, bigint, bigint], Page>,
  'sendFollowRequest' : ActorMethod<[UserId], boolean>,
  'sendMessage' : ActorMethod<[UserId, string], boolean>,
  'toggleLike' : ActorMethod<[PostId], boolean>,
  'unfollowUser' : ActorMethod<[UserId], boolean>,
  'updateCallerProfile' : ActorMethod<[ProfileInput], undefined>,
  'updateCaption' : ActorMethod<[PostId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];