/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorPrincipal' : UserId,
  'postId' : PostId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostInput = IDL.Record({
  'photoBlob' : IDL.Opt(ExternalBlob),
  'caption' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : PostId,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'likeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
  'authorPrincipal' : UserId,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'principal' : UserId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
});
export const DirectMessageView = IDL.Record({
  'id' : IDL.Nat,
  'to' : UserId,
  'from' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'readByRecipient' : IDL.Bool,
});
export const Page_1 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Post),
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Profile),
});
export const Page_4 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(UserId),
});
export const FollowRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const FollowRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : UserId,
  'status' : FollowRequestStatus,
  'from' : UserId,
  'createdAt' : Timestamp,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'newFollower' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'fromPrincipal' : UserId,
  'postId' : IDL.Opt(PostId),
});
export const Page_3 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Notification),
});
export const Page_2 = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Comment),
});
export const ConversationPreview = IDL.Record({
  'lastMessage' : DirectMessageView,
  'unreadCount' : IDL.Nat,
  'partner' : UserId,
});
export const ProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarBlob' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
  'approveFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([PostInput], [Post], []),
  'declineFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteComment' : IDL.Func([PostId, CommentId], [IDL.Bool], []),
  'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
  'followUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [IDL.Vec(DirectMessageView)],
      ['query'],
    ),
  'getExploreFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'getFollowerProfiles' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'getFollowers' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_4], ['query']),
  'getFollowing' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_4], ['query']),
  'getFollowingProfiles' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
  'getMyFollowRequests' : IDL.Func([], [IDL.Vec(FollowRequest)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Page_3], ['query']),
  'getPendingRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'getRequestStatus' : IDL.Func(
      [UserId],
      [IDL.Opt(FollowRequestStatus)],
      ['query'],
    ),
  'getSuggestedUsersWithFollowing' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isLiked' : IDL.Func([PostId], [IDL.Bool], ['query']),
  'listComments' : IDL.Func([PostId, IDL.Nat, IDL.Nat], [Page_2], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'listPostsByAuthor' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [Page_1],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markConversationRead' : IDL.Func([UserId], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'registerUser' : IDL.Func([ProfileInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Page], ['query']),
  'sendFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
  'toggleLike' : IDL.Func([PostId], [IDL.Bool], []),
  'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
  'updateCallerProfile' : IDL.Func([ProfileInput], [], []),
  'updateCaption' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorPrincipal' : UserId,
    'postId' : PostId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostInput = IDL.Record({
    'photoBlob' : IDL.Opt(ExternalBlob),
    'caption' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'likeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
    'authorPrincipal' : UserId,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'principal' : UserId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
  });
  const DirectMessageView = IDL.Record({
    'id' : IDL.Nat,
    'to' : UserId,
    'from' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'readByRecipient' : IDL.Bool,
  });
  const Page_1 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Post),
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Profile),
  });
  const Page_4 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(UserId),
  });
  const FollowRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FollowRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : UserId,
    'status' : FollowRequestStatus,
    'from' : UserId,
    'createdAt' : Timestamp,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'newFollower' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'notifType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'fromPrincipal' : UserId,
    'postId' : IDL.Opt(PostId),
  });
  const Page_3 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Notification),
  });
  const Page_2 = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Comment),
  });
  const ConversationPreview = IDL.Record({
    'lastMessage' : DirectMessageView,
    'unreadCount' : IDL.Nat,
    'partner' : UserId,
  });
  const ProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarBlob' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [Comment], []),
    'approveFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([PostInput], [Post], []),
    'declineFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteComment' : IDL.Func([PostId, CommentId], [IDL.Bool], []),
    'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
    'followUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(DirectMessageView)],
        ['query'],
      ),
    'getExploreFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'getFollowerProfiles' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'getFollowers' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_4], ['query']),
    'getFollowing' : IDL.Func([UserId, IDL.Nat, IDL.Nat], [Page_4], ['query']),
    'getFollowingProfiles' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'getHomeFeed' : IDL.Func([IDL.Nat, IDL.Nat], [Page_1], ['query']),
    'getMyFollowRequests' : IDL.Func([], [IDL.Vec(FollowRequest)], ['query']),
    'getNotifications' : IDL.Func([IDL.Nat, IDL.Nat], [Page_3], ['query']),
    'getPendingRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'getRequestStatus' : IDL.Func(
        [UserId],
        [IDL.Opt(FollowRequestStatus)],
        ['query'],
      ),
    'getSuggestedUsersWithFollowing' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isLiked' : IDL.Func([PostId], [IDL.Bool], ['query']),
    'listComments' : IDL.Func([PostId, IDL.Nat, IDL.Nat], [Page_2], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'listPostsByAuthor' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [Page_1],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markConversationRead' : IDL.Func([UserId], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'registerUser' : IDL.Func([ProfileInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [Page], ['query']),
    'sendFollowRequest' : IDL.Func([UserId], [IDL.Bool], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
    'toggleLike' : IDL.Func([PostId], [IDL.Bool], []),
    'unfollowUser' : IDL.Func([UserId], [IDL.Bool], []),
    'updateCallerProfile' : IDL.Func([ProfileInput], [], []),
    'updateCaption' : IDL.Func([PostId, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };