/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DirectMessageView {
    id: bigint;
    to: UserId;
    from: UserId;
    createdAt: Timestamp;
    text: string;
    readByRecipient: boolean;
}
export type Timestamp = bigint;
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    createdAt: Timestamp;
    text: string;
    authorPrincipal: UserId;
    postId: PostId;
}
export type PostId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Page_2 {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Comment>;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    bio: string;
    postCount: bigint;
    principal: UserId;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
    createdAt: Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}
export interface Page_1 {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Post>;
}
export interface ConversationPreview {
    lastMessage: DirectMessageView;
    unreadCount: bigint;
    partner: UserId;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface Page_3 {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Notification>;
}
export interface Page {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Profile>;
}
export interface Post {
    id: PostId;
    photoBlob?: ExternalBlob;
    likeCount: bigint;
    createdAt: Timestamp;
    caption: string;
    commentCount: bigint;
    authorPrincipal: UserId;
}
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    notifType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    fromPrincipal: UserId;
    postId?: PostId;
}
export interface FollowRequest {
    id: bigint;
    to: UserId;
    status: FollowRequestStatus;
    from: UserId;
    createdAt: Timestamp;
}
export interface PostInput {
    photoBlob?: ExternalBlob;
    caption: string;
}
export interface Page_4 {
    total: bigint;
    nextOffset?: bigint;
    items: Array<UserId>;
}
export interface ProfileInput {
    bio: string;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
}
export interface UserProfile {
    bio: string;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
}
export enum FollowRequestStatus {
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum NotificationType {
    like = "like",
    comment = "comment",
    newFollower = "newFollower"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addComment(postId: PostId, text: string): Promise<Comment>;
    approveFollowRequest(requesterId: UserId): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(input: PostInput): Promise<Post>;
    declineFollowRequest(requesterId: UserId): Promise<boolean>;
    deleteComment(postId: PostId, commentId: CommentId): Promise<boolean>;
    deletePost(postId: PostId): Promise<boolean>;
    followUser(target: UserId): Promise<boolean>;
    getCallerProfile(): Promise<Profile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(withUser: UserId, limit: bigint, offset: bigint): Promise<Array<DirectMessageView>>;
    getExploreFeed(offset: bigint, limit: bigint): Promise<Page_1>;
    getFollowerProfiles(user: UserId, offset: bigint, limit: bigint): Promise<Page>;
    getFollowers(user: UserId, offset: bigint, limit: bigint): Promise<Page_4>;
    getFollowing(user: UserId, offset: bigint, limit: bigint): Promise<Page_4>;
    getFollowingProfiles(user: UserId, offset: bigint, limit: bigint): Promise<Page>;
    getHomeFeed(offset: bigint, limit: bigint): Promise<Page_1>;
    getMyFollowRequests(): Promise<Array<FollowRequest>>;
    getNotifications(offset: bigint, limit: bigint): Promise<Page_3>;
    getPendingRequestCount(): Promise<bigint>;
    getPost(postId: PostId): Promise<Post | null>;
    getProfile(user: UserId): Promise<Profile | null>;
    getRequestStatus(targetId: UserId): Promise<FollowRequestStatus | null>;
    getSuggestedUsersWithFollowing(offset: bigint, limit: bigint): Promise<Page>;
    getUnreadMessageCount(): Promise<bigint>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: UserId): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(target: UserId): Promise<boolean>;
    isLiked(postId: PostId): Promise<boolean>;
    listComments(postId: PostId, offset: bigint, limit: bigint): Promise<Page_2>;
    listConversations(): Promise<Array<ConversationPreview>>;
    listPostsByAuthor(author: UserId, offset: bigint, limit: bigint): Promise<Page_1>;
    markAllNotificationsRead(): Promise<void>;
    markConversationRead(partner: UserId): Promise<void>;
    markNotificationRead(notifId: NotificationId): Promise<boolean>;
    registerUser(input: ProfileInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUsers(queryText: string, offset: bigint, limit: bigint): Promise<Page>;
    sendFollowRequest(to: UserId): Promise<boolean>;
    sendMessage(to: UserId, text: string): Promise<boolean>;
    toggleLike(postId: PostId): Promise<boolean>;
    unfollowUser(target: UserId): Promise<boolean>;
    updateCallerProfile(input: ProfileInput): Promise<void>;
    updateCaption(postId: PostId, newCaption: string): Promise<boolean>;
}
import type { Comment as _Comment, ExternalBlob as _ExternalBlob, FollowRequest as _FollowRequest, FollowRequestStatus as _FollowRequestStatus, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Page as _Page, Page_1 as _Page_1, Page_2 as _Page_2, Page_3 as _Page_3, Page_4 as _Page_4, Post as _Post, PostId as _PostId, PostInput as _PostInput, Profile as _Profile, ProfileInput as _ProfileInput, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addComment(arg0: PostId, arg1: string): Promise<Comment> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async approveFollowRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFollowRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: PostInput): Promise<Post> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_PostInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_PostInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Post_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async declineFollowRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFollowRequest(arg0);
            return result;
        }
    }
    async deleteComment(arg0: PostId, arg1: CommentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Array<DirectMessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0, arg1, arg2);
            return result;
        }
    }
    async getExploreFeed(arg0: bigint, arg1: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getExploreFeed(arg0, arg1);
                return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExploreFeed(arg0, arg1);
            return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowerProfiles(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowerProfiles(arg0, arg1, arg2);
                return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowerProfiles(arg0, arg1, arg2);
            return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Page_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0, arg1, arg2);
                return from_candid_Page_4_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0, arg1, arg2);
            return from_candid_Page_4_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowing(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Page_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0, arg1, arg2);
                return from_candid_Page_4_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0, arg1, arg2);
            return from_candid_Page_4_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowingProfiles(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingProfiles(arg0, arg1, arg2);
                return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingProfiles(arg0, arg1, arg2);
            return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeFeed(arg0: bigint, arg1: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed(arg0, arg1);
                return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed(arg0, arg1);
            return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFollowRequests(): Promise<Array<FollowRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFollowRequests();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFollowRequests();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint, arg1: bigint): Promise<Page_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0, arg1);
                return from_candid_Page_3_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0, arg1);
            return from_candid_Page_3_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRequestCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRequestCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRequestCount();
            return result;
        }
    }
    async getPost(arg0: PostId): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestStatus(arg0: UserId): Promise<FollowRequestStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestStatus(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestStatus(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuggestedUsersWithFollowing(arg0: bigint, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedUsersWithFollowing(arg0, arg1);
                return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedUsersWithFollowing(arg0, arg1);
            return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadMessageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadMessageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadMessageCount();
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async isLiked(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLiked(arg0);
            return result;
        }
    }
    async listComments(arg0: PostId, arg1: bigint, arg2: bigint): Promise<Page_2> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0, arg1, arg2);
                return from_candid_Page_2_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0, arg1, arg2);
            return from_candid_Page_2_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConversations(): Promise<Array<ConversationPreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations();
            return result;
        }
    }
    async listPostsByAuthor(arg0: UserId, arg1: bigint, arg2: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.listPostsByAuthor(arg0, arg1, arg2);
                return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPostsByAuthor(arg0, arg1, arg2);
            return from_candid_Page_1_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markConversationRead(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationRead(arg0);
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: ProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(await to_candid_ProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(await to_candid_ProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUsers(arg0: string, arg1: bigint, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0, arg1, arg2);
                return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0, arg1, arg2);
            return from_candid_Page_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFollowRequest(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFollowRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFollowRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: UserId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async toggleLike(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateCallerProfile(arg0: ProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerProfile(await to_candid_ProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerProfile(await to_candid_ProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCaption(arg0: PostId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaption(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaption(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowRequestStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowRequestStatus): FollowRequestStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_FollowRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowRequest): FollowRequest {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_Page_1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_1): Promise<Page_1> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Page_2_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_2): Page_2 {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Page_3_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_3): Page_3 {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Page_4_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_4): Page_4 {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Page_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Promise<Page> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Promise<Profile | null> {
    return value.length === 0 ? null : await from_candid_Profile_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostId]): PostId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FollowRequestStatus]): FollowRequestStatus | null {
    return value.length === 0 ? null : from_candid_FollowRequestStatus_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    photoBlob: [] | [_ExternalBlob];
    likeCount: bigint;
    createdAt: _Timestamp;
    caption: string;
    commentCount: bigint;
    authorPrincipal: _UserId;
}): Promise<{
    id: PostId;
    photoBlob?: ExternalBlob;
    likeCount: bigint;
    createdAt: Timestamp;
    caption: string;
    commentCount: bigint;
    authorPrincipal: UserId;
}> {
    return {
        id: value.id,
        photoBlob: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.photoBlob)),
        likeCount: value.likeCount,
        createdAt: value.createdAt,
        caption: value.caption,
        commentCount: value.commentCount,
        authorPrincipal: value.authorPrincipal
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    postCount: bigint;
    principal: _UserId;
    username: string;
    displayName: string;
    avatarBlob: [] | [_ExternalBlob];
    createdAt: _Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}): Promise<{
    bio: string;
    postCount: bigint;
    principal: UserId;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
    createdAt: Timestamp;
    followerCount: bigint;
    followingCount: bigint;
}> {
    return {
        bio: value.bio,
        postCount: value.postCount,
        principal: value.principal,
        username: value.username,
        displayName: value.displayName,
        avatarBlob: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.avatarBlob)),
        createdAt: value.createdAt,
        followerCount: value.followerCount,
        followingCount: value.followingCount
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    avatarBlob: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        avatarBlob: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.avatarBlob))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_Post>;
}): Promise<{
    total: bigint;
    nextOffset?: bigint;
    items: Array<Post>;
}> {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: await from_candid_vec_n27(_uploadFile, _downloadFile, value.items)
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_Profile>;
}): Promise<{
    total: bigint;
    nextOffset?: bigint;
    items: Array<Profile>;
}> {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: await from_candid_vec_n30(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_UserId>;
}): {
    total: bigint;
    nextOffset?: bigint;
    items: Array<UserId>;
} {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: value.items
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: _UserId;
    status: _FollowRequestStatus;
    from: _UserId;
    createdAt: _Timestamp;
}): {
    id: bigint;
    to: UserId;
    status: FollowRequestStatus;
    from: UserId;
    createdAt: Timestamp;
} {
    return {
        id: value.id,
        to: value.to,
        status: from_candid_FollowRequestStatus_n36(_uploadFile, _downloadFile, value.status),
        from: value.from,
        createdAt: value.createdAt
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_Notification>;
}): {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Notification>;
} {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: from_candid_vec_n40(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    notifType: _NotificationType;
    createdAt: _Timestamp;
    read: boolean;
    fromPrincipal: _UserId;
    postId: [] | [_PostId];
}): {
    id: NotificationId;
    notifType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    fromPrincipal: UserId;
    postId?: PostId;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n43(_uploadFile, _downloadFile, value.notifType),
        createdAt: value.createdAt,
        read: value.read,
        fromPrincipal: value.fromPrincipal,
        postId: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_Comment>;
}): {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Comment>;
} {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: value.items
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): FollowRequestStatus {
    return "pending" in value ? FollowRequestStatus.pending : "approved" in value ? FollowRequestStatus.approved : "declined" in value ? FollowRequestStatus.declined : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    comment: null;
} | {
    newFollower: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "newFollower" in value ? NotificationType.newFollower : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Promise<Array<Profile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Profile_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowRequest>): Array<FollowRequest> {
    return value.map((x)=>from_candid_FollowRequest_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n41(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PostInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostInput): Promise<_PostInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ProfileInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileInput): Promise<_ProfileInput> {
    return await to_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    photoBlob?: ExternalBlob;
    caption: string;
}): Promise<{
    photoBlob: [] | [_ExternalBlob];
    caption: string;
}> {
    return {
        photoBlob: value.photoBlob ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.photoBlob)) : candid_none(),
        caption: value.caption
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    avatarBlob?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    displayName: string;
    avatarBlob: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        avatarBlob: value.avatarBlob ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.avatarBlob)) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
